[project]
name = "farmer-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.2.0",
    "colorlog>=6.10.1",
    "fastapi>=0.135.3",
    "google-generativeai>=0.8.5",
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "langchain-groq>=1.1.2",
    "langchainhub>=0.1.21",
    "pillow>=11.3.0",
    "python-dotenv>=1.2.2",
    "python-telegram-bot>=22.7",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "matplotlib>=3.10.7",
    "requests>=2.33.1",
    "schedule>=1.2.2",
    "sentence-transformers>=5.1.2",
    "python-multipart>=0.0.20",
    "uvicorn>=0.44.0",
    "websocket>=0.2.1",
    "websockets>=16.0",
]
